[keyboard]
name = "macropad"
product_name = "macropad"
vendor_id = 0x4c4b
product_id = 0x4643
manufacturer = "RMK"
chip = "rp2040"

[matrix]
matrix_type = "direct_pin"
direct_pins = [
    ["PIN_11", "PIN_10", "PIN_9"]
]

direct_pin_low_active = true

[layout]
rows = 1
cols = 3
layers = 1
matrix_map = "(0,0) (0,1) (0,2)"

[[layer]]
name = "base"
keys = "F13 F14 F15"
